"""final models and relationships

Revision ID: 069ba543bea2
Revises: 2a1aea3c4140
Create Date: 2023-08-01 15:55:39.447272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069ba543bea2'
down_revision = '2a1aea3c4140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    with op.batch_alter_table('Units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Units_unit_name'), ['unit_name'], unique=False)

    op.create_table('Assessment',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('assessment_name', sa.String(length=255), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['Units.unit_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    with op.batch_alter_table('Assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Assessment_assessment_name'), ['assessment_name'], unique=False)

    op.create_table('student_units',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('units_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.ForeignKeyConstraint(['units_id'], ['Units.unit_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'units_id')
    )
    op.create_table('Grades',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['Assessment.assessment_id'], ),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_table('Response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    with op.batch_alter_table('Response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Response_subject'), ['subject'], unique=False)

    op.create_table('enquiry',
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Parents.parent_id'], ),
    sa.PrimaryKeyConstraint('enquiry_id')
    )
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiry_subject'), ['subject'], unique=False)

    op.create_table('student_assessment',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['Assessment.assessment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'assessment_id')
    )
    op.create_table('student_grade',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['Grades.grade_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'grade_id')
    )
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    op.drop_table('student_grade')
    op.drop_table('student_assessment')
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiry_subject'))

    op.drop_table('enquiry')
    with op.batch_alter_table('Response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Response_subject'))

    op.drop_table('Response')
    op.drop_table('Grades')
    op.drop_table('student_units')
    with op.batch_alter_table('Assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Assessment_assessment_name'))

    op.drop_table('Assessment')
    with op.batch_alter_table('Units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Units_unit_name'))

    op.drop_table('Units')
    # ### end Alembic commands ###
