"""new models and relationships

Revision ID: 2a1aea3c4140
Revises: e433f7af46ab
Create Date: 2023-08-01 13:50:12.364909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1aea3c4140'
down_revision = 'e433f7af46ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=False),
    sa.Column('hod_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('Payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('Payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Payments_payment_type'), ['payment_type'], unique=False)

    op.create_table('Course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['Departments.department_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    with op.batch_alter_table('Course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Course_course_name'), ['course_name'], unique=False)

    op.create_table('StudentAttendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_table('LeaveOfAbsence',
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('leave_id')
    )
    op.create_table('TeacherAttendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Course', ['course_id'], ['course_id'])
        batch_op.create_foreign_key(None, 'Payments', ['payment_id'], ['payment_id'])
        batch_op.create_foreign_key(None, 'Departments', ['department_id'], ['department_id'])
        batch_op.drop_column('course')

    with op.batch_alter_table('Teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Departments', ['department_id'], ['department_id'])
        batch_op.create_foreign_key(None, 'Course', ['course_id'], ['course_id'])
        batch_op.drop_column('course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('course_id')
        batch_op.drop_column('department_id')

    op.drop_table('TeacherAttendance')
    op.drop_table('LeaveOfAbsence')
    op.drop_table('StudentAttendance')
    with op.batch_alter_table('Course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Course_course_name'))

    op.drop_table('Course')
    with op.batch_alter_table('Payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Payments_payment_type'))

    op.drop_table('Payments')
    op.drop_table('Departments')
    # ### end Alembic commands ###
