"""new

Revision ID: 36ea2376e0e0
Revises: 
Create Date: 2023-07-31 15:25:30.092063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ea2376e0e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('leaves')
    op.drop_table('expenses')
    op.drop_table('students')
    op.drop_table('student_attendance')
    op.drop_table('departments')
    op.drop_table('admins')
    op.drop_table('guardian_student')
    op.drop_table('teacher_attendance')
    op.drop_table('payrolls')
    op.drop_table('courses')
    op.drop_table('guardians')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardians',
    sa.Column('tel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('guardians_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='guardians_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='courses_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payrolls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='payrolls_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payrolls_pkey')
    )
    op.create_table('teacher_attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teacher_attendance_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teacher_attendance_pkey')
    )
    op.create_table('guardian_student',
    sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name='guardian_student_guardian_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='guardian_student_student_id_fkey'),
    sa.PrimaryKeyConstraint('guardian_id', 'student_id', name='guardian_student_pkey')
    )
    op.create_table('admins',
    sa.Column('tel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('departments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('student_attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_attendance_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_attendance_pkey')
    )
    op.create_table('students',
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('enrolment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fee_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='students_course_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='students_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('expense_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='expenses_pkey')
    )
    op.create_table('leaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='leaves_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leaves_pkey')
    )
    op.create_table('teachers',
    sa.Column('tel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='teachers_course_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='teachers_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teachers_pkey')
    )
    # ### end Alembic commands ###
