"""Edited student-teacher relationship

Revision ID: 6cd7234e3f1f
Revises: 
Create Date: 2023-08-02 12:17:16.794599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd7234e3f1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint('teachers_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('teachers_student_id_fkey', 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
