"""done

Revision ID: 70a78c7cf5e1
Revises: ab028f7d7824
Create Date: 2023-08-07 15:07:46.051137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a78c7cf5e1'
down_revision = 'ab028f7d7824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_assessment')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint('assessments_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('assessments_student_id_fkey', 'students', ['student_id'], ['student_id'])

    op.create_table('student_assessment',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name='student_assessment_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='student_assessment_student_id_fkey'),
    sa.PrimaryKeyConstraint('student_id', 'assessment_id', name='student_assessment_pkey')
    )
    # ### end Alembic commands ###
