"""Edited models

Revision ID: 7bf0045a88ea
Revises: 
Create Date: 2023-08-02 06:29:00.990875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf0045a88ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_of_absence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('leave_of_absence', schema=None) as batch_op:
        batch_op.drop_column('end')

    # ### end Alembic commands ###
