"""New

Revision ID: 96e98be7f877
Revises: 
Create Date: 2023-08-04 19:05:39.896802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e98be7f877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['department_name'])

    with op.batch_alter_table('leave_of_absence', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('DOB')

    with op.batch_alter_table('student_assessment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['assessment_id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('student_grade', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.create_foreign_key(None, 'grades', ['grade_id'], ['grade_id'])

    with op.batch_alter_table('student_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['unit_id'])
        batch_op.drop_column('units_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['teacher_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('superadmins', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index('ix_teachers_last_name')
        batch_op.create_index(batch_op.f('ix_teachers_last_name'), ['last_name'], unique=True)
        batch_op.drop_constraint('teachers_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('student_id')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('ix_units_unit_name')
        batch_op.create_index(batch_op.f('ix_units_unit_name'), ['unit_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_unit_name'))
        batch_op.create_index('ix_units_unit_name', ['unit_name'], unique=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teachers_student_id_fkey', 'students', ['student_id'], ['student_id'])
        batch_op.drop_index(batch_op.f('ix_teachers_last_name'))
        batch_op.create_index('ix_teachers_last_name', ['last_name'], unique=False)

    with op.batch_alter_table('superadmins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('student_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit_id')

    with op.batch_alter_table('student_grade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('student_assessment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DOB', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('leave_of_absence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=25), autoincrement=False, nullable=True))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
