"""Grades id rename

Revision ID: b41a7c54507b
Revises: ba12d4a87b62
Create Date: 2023-08-07 21:55:03.531368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41a7c54507b'
down_revision = 'ba12d4a87b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
