"""Grades cascade

Revision ID: ba12d4a87b62
Revises: 70a78c7cf5e1
Create Date: 2023-08-07 21:51:50.905827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba12d4a87b62'
down_revision = '70a78c7cf5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('grades_assessment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['assessment_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_assessment_id_fkey', 'assessments', ['assessment_id'], ['assessment_id'])

    # ### end Alembic commands ###
