"""initial migration

Revision ID: e433f7af46ab
Revises: 
Create Date: 2023-07-31 14:12:47.148313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e433f7af46ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=65), nullable=False),
    sa.Column('user_type', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_name'), ['user_name'], unique=True)

    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('DOB', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('employment_date', sa.String(length=100), nullable=False),
    sa.Column('appraisal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Admin_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Admin_last_name'), ['last_name'], unique=False)

    op.create_table('Students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('DOB', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('enrollment_date', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Students_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Students_last_name'), ['last_name'], unique=False)

    op.create_table('SuperAdmin',
    sa.Column('super_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('DOB', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('employment_date', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('super_id')
    )
    with op.batch_alter_table('SuperAdmin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SuperAdmin_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_SuperAdmin_last_name'), ['last_name'], unique=False)

    op.create_table('Parents',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('DOB', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    with op.batch_alter_table('Parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Parents_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Parents_last_name'), ['last_name'], unique=False)

    op.create_table('Teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('DOB', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('employment_date', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('appraisal', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    with op.batch_alter_table('Teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Teachers_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Teachers_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Teachers_last_name'))
        batch_op.drop_index(batch_op.f('ix_Teachers_first_name'))

    op.drop_table('Teachers')
    with op.batch_alter_table('Parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Parents_last_name'))
        batch_op.drop_index(batch_op.f('ix_Parents_first_name'))

    op.drop_table('Parents')
    with op.batch_alter_table('SuperAdmin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SuperAdmin_last_name'))
        batch_op.drop_index(batch_op.f('ix_SuperAdmin_first_name'))

    op.drop_table('SuperAdmin')
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Students_last_name'))
        batch_op.drop_index(batch_op.f('ix_Students_first_name'))

    op.drop_table('Students')
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Admin_last_name'))
        batch_op.drop_index(batch_op.f('ix_Admin_first_name'))

    op.drop_table('Admin')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
