"""Deleted dob on parent

Revision ID: e5833ef8c464
Revises: 6cd7234e3f1f
Create Date: 2023-08-03 12:23:10.756422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5833ef8c464'
down_revision = '6cd7234e3f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['department_name'])

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('DOB')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index('ix_teachers_last_name')
        batch_op.create_index(batch_op.f('ix_teachers_last_name'), ['last_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_last_name'))
        batch_op.create_index('ix_teachers_last_name', ['last_name'], unique=False)

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DOB', sa.DATE(), autoincrement=False, nullable=False))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
